name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js 20
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm test
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
